# Generated by Django 5.0.6 on 2024-11-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_user_cartitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
