# Generated by Django 5.0.6 on 2024-11-15 13:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0004_remove_products_stock_variant_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Order2',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItem2',
        ),
    ]
