# Generated by Django 5.0.6 on 2024-10-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_otp_otp_otp_code_remove_otp_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
