# Generated by Django 5.0.6 on 2024-11-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_variant_stock_products_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
        migrations.AddField(
            model_name='variant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
